services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
        POSTGRES_URL_NON_POOLING: ${POSTGRES_URL_NON_POOLING}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_URL_NO_SSL=${POSTGRES_URL_NO_SSL}
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: always